//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Compra_Cabecera = new HashSet<Compra_Cabecera>();
        }
    
        public int idCliente { get; set; }
        public string nomCliente { get; set; }
        public string apeCliente { get; set; }
        public string dniCliente { get; set; }
        public string tlfCliente { get; set; }
        public string direcCliente { get; set; }
        public int idDistrito { get; set; }
        public string emailCliente { get; set; }
        public string passCliente { get; set; }
        public int idTipoUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Cabecera> Compra_Cabecera { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
