//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra_Cabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra_Cabecera()
        {
            this.Compra_Detalle = new HashSet<Compra_Detalle>();
        }
    
        public int idCompra { get; set; }
        public int idCliente { get; set; }
        public System.DateTime fec_ped_comp { get; set; }
        public System.DateTime fec_ent_comp { get; set; }
        public int est_comp { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Detalle> Compra_Detalle { get; set; }
    }
}
