//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int idEmpleado { get; set; }
        public string nomEmpleado { get; set; }
        public string apeEmpleado { get; set; }
        public string dniEmpleado { get; set; }
        public string tlfEmpleado { get; set; }
        public string direcEmpleado { get; set; }
        public int idDistrito { get; set; }
        public int idCargo { get; set; }
        public string emailEmpleado { get; set; }
        public string passEmpleado { get; set; }
        public int idTipoUsuario { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
