//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnologyStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TechnologyDataEntities : DbContext
    {
        public TechnologyDataEntities()
            : base("name=TechnologyDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Compra_Cabecera> Compra_Cabecera { get; set; }
        public virtual DbSet<Compra_Detalle> Compra_Detalle { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
    
        public virtual ObjectResult<usp_detalle_producto_Result> usp_detalle_producto(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_detalle_producto_Result>("usp_detalle_producto", codParameter);
        }
    
        public virtual ObjectResult<usp_listar_productos_Result> usp_listar_productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_productos_Result>("usp_listar_productos");
        }
    
        public virtual ObjectResult<Nullable<int>> usp_logincliente(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_logincliente", emailParameter, passParameter);
        }
    
        public virtual int usp_transaccion_compra_cabecera(Nullable<int> id_comp, Nullable<int> cod_cli, Nullable<System.DateTime> fec_ped_comp, Nullable<System.DateTime> fec_ent_comp, Nullable<int> est_comp, Nullable<int> tipo)
        {
            var id_compParameter = id_comp.HasValue ?
                new ObjectParameter("id_comp", id_comp) :
                new ObjectParameter("id_comp", typeof(int));
    
            var cod_cliParameter = cod_cli.HasValue ?
                new ObjectParameter("cod_cli", cod_cli) :
                new ObjectParameter("cod_cli", typeof(int));
    
            var fec_ped_compParameter = fec_ped_comp.HasValue ?
                new ObjectParameter("fec_ped_comp", fec_ped_comp) :
                new ObjectParameter("fec_ped_comp", typeof(System.DateTime));
    
            var fec_ent_compParameter = fec_ent_comp.HasValue ?
                new ObjectParameter("fec_ent_comp", fec_ent_comp) :
                new ObjectParameter("fec_ent_comp", typeof(System.DateTime));
    
            var est_compParameter = est_comp.HasValue ?
                new ObjectParameter("est_comp", est_comp) :
                new ObjectParameter("est_comp", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_transaccion_compra_cabecera", id_compParameter, cod_cliParameter, fec_ped_compParameter, fec_ent_compParameter, est_compParameter, tipoParameter);
        }
    
        public virtual int usp_insertar_compra_detalle(Nullable<int> id_comp, Nullable<int> cod_prod, Nullable<int> cantidad)
        {
            var id_compParameter = id_comp.HasValue ?
                new ObjectParameter("id_comp", id_comp) :
                new ObjectParameter("id_comp", typeof(int));
    
            var cod_prodParameter = cod_prod.HasValue ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(int));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insertar_compra_detalle", id_compParameter, cod_prodParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<usp_detalle_compra_Result> usp_detalle_compra(Nullable<int> idcomp)
        {
            var idcompParameter = idcomp.HasValue ?
                new ObjectParameter("idcomp", idcomp) :
                new ObjectParameter("idcomp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_detalle_compra_Result>("usp_detalle_compra", idcompParameter);
        }
    
        public virtual int usp_registrar_cliente(string nomcli, string apecli, string dnicli, string tlfcli, string dircli, Nullable<int> iddist, string emailcli, string passcli)
        {
            var nomcliParameter = nomcli != null ?
                new ObjectParameter("nomcli", nomcli) :
                new ObjectParameter("nomcli", typeof(string));
    
            var apecliParameter = apecli != null ?
                new ObjectParameter("apecli", apecli) :
                new ObjectParameter("apecli", typeof(string));
    
            var dnicliParameter = dnicli != null ?
                new ObjectParameter("dnicli", dnicli) :
                new ObjectParameter("dnicli", typeof(string));
    
            var tlfcliParameter = tlfcli != null ?
                new ObjectParameter("tlfcli", tlfcli) :
                new ObjectParameter("tlfcli", typeof(string));
    
            var dircliParameter = dircli != null ?
                new ObjectParameter("dircli", dircli) :
                new ObjectParameter("dircli", typeof(string));
    
            var iddistParameter = iddist.HasValue ?
                new ObjectParameter("iddist", iddist) :
                new ObjectParameter("iddist", typeof(int));
    
            var emailcliParameter = emailcli != null ?
                new ObjectParameter("emailcli", emailcli) :
                new ObjectParameter("emailcli", typeof(string));
    
            var passcliParameter = passcli != null ?
                new ObjectParameter("passcli", passcli) :
                new ObjectParameter("passcli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_registrar_cliente", nomcliParameter, apecliParameter, dnicliParameter, tlfcliParameter, dircliParameter, iddistParameter, emailcliParameter, passcliParameter);
        }
    
        public virtual int usp_editar_cliente(Nullable<int> codcli, string nomcli, string apecli, Nullable<int> iddist, string dircli, string tlfcli, string passcli)
        {
            var codcliParameter = codcli.HasValue ?
                new ObjectParameter("codcli", codcli) :
                new ObjectParameter("codcli", typeof(int));
    
            var nomcliParameter = nomcli != null ?
                new ObjectParameter("nomcli", nomcli) :
                new ObjectParameter("nomcli", typeof(string));
    
            var apecliParameter = apecli != null ?
                new ObjectParameter("apecli", apecli) :
                new ObjectParameter("apecli", typeof(string));
    
            var iddistParameter = iddist.HasValue ?
                new ObjectParameter("iddist", iddist) :
                new ObjectParameter("iddist", typeof(int));
    
            var dircliParameter = dircli != null ?
                new ObjectParameter("dircli", dircli) :
                new ObjectParameter("dircli", typeof(string));
    
            var tlfcliParameter = tlfcli != null ?
                new ObjectParameter("tlfcli", tlfcli) :
                new ObjectParameter("tlfcli", typeof(string));
    
            var passcliParameter = passcli != null ?
                new ObjectParameter("passcli", passcli) :
                new ObjectParameter("passcli", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_editar_cliente", codcliParameter, nomcliParameter, apecliParameter, iddistParameter, dircliParameter, tlfcliParameter, passcliParameter);
        }
    
        public virtual ObjectResult<usp_adm_listar_empleados_Result> usp_adm_listar_empleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_listar_empleados_Result>("usp_adm_listar_empleados");
        }
    
        public virtual ObjectResult<Nullable<int>> usp_adm_loginadmin(string email, string pass)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_adm_loginadmin", emailParameter, passParameter);
        }
    
        public virtual int usp_adm_registrar_empleado(string nombre, string apellido, string dni, string telefono, string direccion, Nullable<int> coddis, Nullable<int> codcargo, string email, string pass, Nullable<int> codtipusu)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var coddisParameter = coddis.HasValue ?
                new ObjectParameter("coddis", coddis) :
                new ObjectParameter("coddis", typeof(int));
    
            var codcargoParameter = codcargo.HasValue ?
                new ObjectParameter("codcargo", codcargo) :
                new ObjectParameter("codcargo", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var codtipusuParameter = codtipusu.HasValue ?
                new ObjectParameter("codtipusu", codtipusu) :
                new ObjectParameter("codtipusu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_registrar_empleado", nombreParameter, apellidoParameter, dniParameter, telefonoParameter, direccionParameter, coddisParameter, codcargoParameter, emailParameter, passParameter, codtipusuParameter);
        }
    
        public virtual int usp_adm_actualizar_empleado(Nullable<int> codigo, string nombre, string apellido, string dni, string telefono, string direccion, Nullable<int> iddistrito, Nullable<int> idcargo, string email, string pass, Nullable<int> idtipusu)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var iddistritoParameter = iddistrito.HasValue ?
                new ObjectParameter("iddistrito", iddistrito) :
                new ObjectParameter("iddistrito", typeof(int));
    
            var idcargoParameter = idcargo.HasValue ?
                new ObjectParameter("idcargo", idcargo) :
                new ObjectParameter("idcargo", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var idtipusuParameter = idtipusu.HasValue ?
                new ObjectParameter("idtipusu", idtipusu) :
                new ObjectParameter("idtipusu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_actualizar_empleado", codigoParameter, nombreParameter, apellidoParameter, dniParameter, telefonoParameter, direccionParameter, iddistritoParameter, idcargoParameter, emailParameter, passParameter, idtipusuParameter);
        }
    
        public virtual int usp_adm_cargo_actualizar(Nullable<int> codigo, string nombre)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_cargo_actualizar", codigoParameter, nombreParameter);
        }
    
        public virtual int usp_adm_cargo_eliminar(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_cargo_eliminar", codigoParameter);
        }
    
        public virtual ObjectResult<usp_adm_cargo_listar_Result> usp_adm_cargo_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_cargo_listar_Result>("usp_adm_cargo_listar");
        }
    
        public virtual int usp_adm_cargo_registrar(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_cargo_registrar", nombreParameter);
        }
    
        public virtual int usp_adm_categoria_actualizar(Nullable<int> codigo, string nombre)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_categoria_actualizar", codigoParameter, nombreParameter);
        }
    
        public virtual int usp_adm_categoria_eliminar(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_categoria_eliminar", codigoParameter);
        }
    
        public virtual ObjectResult<usp_adm_categoria_listar_Result> usp_adm_categoria_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_categoria_listar_Result>("usp_adm_categoria_listar");
        }
    
        public virtual int usp_adm_categoria_registrar(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_categoria_registrar", nombreParameter);
        }
    
        public virtual int usp_adm_cliente_actualizar(Nullable<int> codigo, string nombre, string apellido, string dni, string telefono, string direccion, Nullable<int> distrito, string correo, string password)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var distritoParameter = distrito.HasValue ?
                new ObjectParameter("distrito", distrito) :
                new ObjectParameter("distrito", typeof(int));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_cliente_actualizar", codigoParameter, nombreParameter, apellidoParameter, dniParameter, telefonoParameter, direccionParameter, distritoParameter, correoParameter, passwordParameter);
        }
    
        public virtual int usp_adm_cliente_eliminar(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_cliente_eliminar", codigoParameter);
        }
    
        public virtual ObjectResult<usp_adm_cliente_listar_Result> usp_adm_cliente_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_cliente_listar_Result>("usp_adm_cliente_listar");
        }
    
        public virtual ObjectResult<usp_adm_compra_lista_Result> usp_adm_compra_lista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_compra_lista_Result>("usp_adm_compra_lista");
        }
    
        public virtual int usp_adm_distrito_actualizar(Nullable<int> codigo, string nombre)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_distrito_actualizar", codigoParameter, nombreParameter);
        }
    
        public virtual int usp_adm_distrito_eliminar(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_distrito_eliminar", codigoParameter);
        }
    
        public virtual ObjectResult<usp_adm_distrito_listar_Result> usp_adm_distrito_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_distrito_listar_Result>("usp_adm_distrito_listar");
        }
    
        public virtual int usp_adm_distrito_registrar(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_distrito_registrar", nombreParameter);
        }
    
        public virtual int usp_adm_eliminar_empleado(Nullable<int> codigoemp)
        {
            var codigoempParameter = codigoemp.HasValue ?
                new ObjectParameter("codigoemp", codigoemp) :
                new ObjectParameter("codigoemp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_eliminar_empleado", codigoempParameter);
        }
    
        public virtual int usp_adm_producto_actualizar(Nullable<int> codigo, string descripcion, Nullable<decimal> precio, Nullable<int> stockact, Nullable<int> stockmin, Nullable<int> idcateg)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var stockactParameter = stockact.HasValue ?
                new ObjectParameter("stockact", stockact) :
                new ObjectParameter("stockact", typeof(int));
    
            var stockminParameter = stockmin.HasValue ?
                new ObjectParameter("stockmin", stockmin) :
                new ObjectParameter("stockmin", typeof(int));
    
            var idcategParameter = idcateg.HasValue ?
                new ObjectParameter("idcateg", idcateg) :
                new ObjectParameter("idcateg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_producto_actualizar", codigoParameter, descripcionParameter, precioParameter, stockactParameter, stockminParameter, idcategParameter);
        }
    
        public virtual int usp_adm_producto_eliminar(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_producto_eliminar", codigoParameter);
        }
    
        public virtual ObjectResult<usp_adm_producto_listar_Result> usp_adm_producto_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_producto_listar_Result>("usp_adm_producto_listar");
        }
    
        public virtual int usp_adm_producto_registrar(string descripcion, Nullable<decimal> precio, Nullable<int> stockact, Nullable<int> stockmin, Nullable<int> idcateg)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var stockactParameter = stockact.HasValue ?
                new ObjectParameter("stockact", stockact) :
                new ObjectParameter("stockact", typeof(int));
    
            var stockminParameter = stockmin.HasValue ?
                new ObjectParameter("stockmin", stockmin) :
                new ObjectParameter("stockmin", typeof(int));
    
            var idcategParameter = idcateg.HasValue ?
                new ObjectParameter("idcateg", idcateg) :
                new ObjectParameter("idcateg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_producto_registrar", descripcionParameter, precioParameter, stockactParameter, stockminParameter, idcategParameter);
        }
    
        public virtual int usp_adm_tipousuario_actualizar(Nullable<int> codigo, string nombre)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_tipousuario_actualizar", codigoParameter, nombreParameter);
        }
    
        public virtual int usp_adm_tipousuario_eliminar(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_tipousuario_eliminar", codigoParameter);
        }
    
        public virtual ObjectResult<usp_adm_tipousuario_listar_Result> usp_adm_tipousuario_listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_adm_tipousuario_listar_Result>("usp_adm_tipousuario_listar");
        }
    
        public virtual int usp_adm_tipousuario_registrar(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_adm_tipousuario_registrar", nombreParameter);
        }
    }
}
